package org.facturation.backend.security;

import org.facturation.backend.model.RoleCode;

import java.util.EnumSet;
import java.util.Set;

public enum BusinessPermission {
    VIEW_OWN_PROFILE(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    VIEW_REFERENCE_DATA(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    VIEW_ORGANIZATION(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    MANAGE_ORGANIZATION(RoleCode.ADMIN),
    VIEW_INVOICES(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    COMMENT_INVOICES(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    VIEW_DASHBOARD(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    VIEW_NOTIFICATIONS(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    PROCESS_INVOICES(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE),
    VALIDATE_INVOICES(RoleCode.RESPONSABLE_COMPTABLE),
    MANAGE_ACCOUNTING_ENTRIES(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    EXPORT_ACCOUNTING(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    CONFIRM_INVOICE_PAYMENTS(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    ARCHIVE_INVOICES(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    VIEW_SUPPLIERS(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    MANAGE_SUPPLIERS(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE),
    VIEW_ACCOUNTING_CONFIGURATION(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    MANAGE_ACCOUNTING_CONFIGURATION(RoleCode.ADMIN),
    VIEW_CLASSIFICATIONS(RoleCode.ADMIN, RoleCode.OPERATEUR_COMPTABLE, RoleCode.RESPONSABLE_COMPTABLE),
    MANAGE_CLASSIFICATIONS(RoleCode.ADMIN),
    MANAGE_USERS(RoleCode.ADMIN);

    private final Set<RoleCode> roles;

    BusinessPermission(RoleCode firstRole, RoleCode... otherRoles) {
        this.roles = EnumSet.of(firstRole, otherRoles);
    }

    public Set<RoleCode> getRoles() {
        return Set.copyOf(roles);
    }

    public String[] roleCodes() {
        return roles.stream()
                .map(RoleCode::getCode)
                .toArray(String[]::new);
    }
}
