export const invoiceStatusLabels: Record<string, string> = {
  A_VERIFIER: 'Waiting approval',
  ARCHIVEE: 'Archived',
  COMPTABILISEE: 'Accounted',
  DEPOSEE: 'To process',
  DUPLICATE_SUSPECTED: 'Duplicate suspected',
  ERREUR_OCR: 'OCR error',
  ERREUR_TRAITEMENT: 'Processing error',
  EXPORTEE: 'Exported',
  EXPORTABLE: 'Ready to export',
  EXTRAITE: 'Needs review',
  OCR_EN_COURS: 'Processing',
  PAYEE: 'Paid',
  REJETEE: 'Rejected',
  VALIDEE: 'Approved',
}
