ALTER TABLE IF EXISTS invoices ADD COLUMN IF NOT EXISTS origin VARCHAR(30);
UPDATE invoices SET origin = 'MANUAL_UPLOAD' WHERE origin IS NULL;
ALTER TABLE invoices ALTER COLUMN origin SET DEFAULT 'MANUAL_UPLOAD';
ALTER TABLE invoices ALTER COLUMN origin SET NOT NULL;
