ALTER TABLE invoices ALTER COLUMN supplier_id DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN invoice_number DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN invoice_date DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN total_ht DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN total_tva DROP NOT NULL;
ALTER TABLE invoices ALTER COLUMN total_ttc DROP NOT NULL;
